# conda env create -f .github/genesis4-build-env-mpich.yml
name: genesis4-build-mpich
channels:
  - conda-forge
dependencies:
  - compilers
  - cmake
  - fftw * mpi_mpich*
  - hdf5 * mpi_mpich*
  - mpich
