name: Documentation

on:
  pull_request:
  push:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build docs"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up the documentation destination
        run: |
          mkdir site/
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --standalone
            --output=site/index.html
            manual/MANUAL.md
            manual/INSTALLATION.md
            manual/MAIN_INPUT.md
            manual/LATTICE.md
            manual/XGENESIS.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --standalone
            --output=genesis4.pdf
            manual/MANUAL.md
            manual/INSTALLATION.md
            manual/MAIN_INPUT.md
            manual/LATTICE.md
            manual/XGENESIS.md
            -V 'mainfont:SansSerif.ttf' 
            -V geometry:margin=1in 
            -V colorlinks=true 
            -V linkcolor=blue 
            -V urlcolor=red 
            -V toccolor=gray
            -s
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: genesis4.pdf
          path: genesis4.pdf
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
  deploy:
    if: ${{ github.repository_owner == 'svenreiche' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}
    needs: build
    name: "Deploy docs"

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
